// Automatically generated by https://honeythecodewitch.com/gfx/icon-pack
// #define CONNECTIVITY_IMPLEMENTATION in exactly one
// translation unit (.cpp file) before including this header
#ifndef CONNECTIVITY_HPP
#define CONNECTIVITY_HPP
#include <stdint.h>
#include "gfx_core.hpp"
#include "gfx_positioning.hpp"
#define CONNECTIVITY_HEIGHT 32

/// @brief "Wifi" dimensions
constexpr static const gfx::sizef connectivity_wifi_dimensions(640,512);
/// @brief "Wifi" scaled dimensions
constexpr static const gfx::size16 connectivity_wifi_scaled_dimensions(40,32);
/// @brief "Wifi" target scale
constexpr static const float connectivity_wifi_scale = 0.0625;
/// @brief "Wifi" - a SVG vector icon
extern gfx::const_buffer_stream connectivity_wifi;
/// @brief "Bluetooth" dimensions
constexpr static const gfx::sizef connectivity_bluetooth_b_dimensions(320,512);
/// @brief "Bluetooth" scaled dimensions
constexpr static const gfx::size16 connectivity_bluetooth_b_scaled_dimensions(20,32);
/// @brief "Bluetooth" target scale
constexpr static const float connectivity_bluetooth_b_scale = 0.0625;
/// @brief "Bluetooth" - a SVG vector icon
extern gfx::const_buffer_stream connectivity_bluetooth_b;
/// @brief "Ethernet" dimensions
constexpr static const gfx::sizef connectivity_ethernet_dimensions(512,512);
/// @brief "Ethernet" scaled dimensions
constexpr static const gfx::size16 connectivity_ethernet_scaled_dimensions(32,32);
/// @brief "Ethernet" target scale
constexpr static const float connectivity_ethernet_scale = 0.0625;
/// @brief "Ethernet" - a SVG vector icon
extern gfx::const_buffer_stream connectivity_ethernet;
#endif // CONNECTIVITY_HPP

#ifdef CONNECTIVITY_IMPLEMENTATION
static const char* connectivity_wifi_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" "
    "viewBox=\"0 0 640 512\"><path d=\"M54.2 202.9C123.2 136.7 216.8 96 320 96s196.8 40."
    "7 265.8 106.9c12.8 12.2 33 11.8 45.2-.9s11.8-33-.9-45.2C549.7 79.5 440.4 32 320 "
    "32S90.3 79.5 9.8 156.7C-2.9 169-3.3 189.2 8.9 202s32.5 13.2 45.2 .9zM320 256c56."
    "8 0 108.6 21.1 148.2 56c13.3 11.7 33.5 10.4 45.2-2.8s10.4-33.5-2.8-45.2C459.8 21"
    "9.2 393 192 320 192s-139.8 27.2-190.5 72c-13.3 11.7-14.5 31.9-2.8 45.2s31.9 14.5"
    " 45.2 2.8c39.5-34.9 91.3-56 148.2-56zm64 160a64 64 0 1 0 -128 0 64 64 0 1 0 128 "
    "0z\"/></svg>";
gfx::const_buffer_stream connectivity_wifi
    ((const uint8_t*)connectivity_wifi_data,531);

static const char* connectivity_bluetooth_b_data = "<svg xmlns=\"http://www.w3.org/200"
    "0/svg\" viewBox=\"0 0 320 512\"><path d=\"M196.48 260.023l92.626-103.333L143.125 0v2"
    "06.33l-86.111-86.111-31.406 31.405 108.061 108.399L25.608 368.422l31.406 31.405 "
    "86.111-86.111L145.84 512l148.552-148.644-97.912-103.333zm40.86-102.996l-49.977 4"
    "9.978-.338-100.295 50.315 50.317zM187.363 313.04l49.977 49.978-50.315 50.316.338"
    "-100.294z\"/></svg>";
gfx::const_buffer_stream connectivity_bluetooth_b
    ((const uint8_t*)connectivity_bluetooth_b_data,371);

static const char* connectivity_ethernet_data = "<svg xmlns=\"http://www.w3.org/2000/s"
    "vg\" viewBox=\"0 0 512 512\"><path d=\"M0 224L0 416c0 17.7 14.3 32 32 32l64 0 0-112c"
    "0-8.8 7.2-16 16-16s16 7.2 16 16l0 112 64 0 0-112c0-8.8 7.2-16 16-16s16 7.2 16 16"
    "l0 112 64 0 0-112c0-8.8 7.2-16 16-16s16 7.2 16 16l0 112 64 0 0-112c0-8.8 7.2-16 "
    "16-16s16 7.2 16 16l0 112 64 0c17.7 0 32-14.3 32-32l0-192c0-17.7-14.3-32-32-32l-3"
    "2 0 0-32c0-17.7-14.3-32-32-32l-32 0 0-32c0-17.7-14.3-32-32-32L160 64c-17.7 0-32 "
    "14.3-32 32l0 32-32 0c-17.7 0-32 14.3-32 32l0 32-32 0c-17.7 0-32 14.3-32 32z\"/></"
    "svg>";
gfx::const_buffer_stream connectivity_ethernet
    ((const uint8_t*)connectivity_ethernet_data,520);
#endif // CONNECTIVITY_IMPLEMENTATION
